export const vehiclesData = {
  bikes: [
    { id: 1, make: 'Royal Enfield', model: 'Classic 350', price: 1200, type: 'bike',image: 'classic350.jpeg' },
    { id: 2, make: 'Royal Enfield', model: 'GT 650', price: 2000, type: 'bike', image: 'gt650.jpeg' },
    { id: 3, make: 'Royal Enfield', model: 'Guerrilla 450', price: 1500, type: 'bike', image: 'guerrilla450.jpg' },
    { id: 4, make: 'Royal Enfield', model: 'Himalayan', price: 1500, type: 'bike', image: 'himalayan.avif' },
    { id: 5, make: 'Royal Enfield', model: 'Hunter 350', price: 1300, type: 'bike', image: 'hunter350.jpg' },
    { id: 6, make: 'Royal Enfield', model: 'Meteor 350', price: 1200, type: 'bike', image: 'meteor350.png' },
    { id: 7, make: 'Hero', model: 'X pluse', price: 1500, type: 'bike', image: 'heroxpulse.webp' },
    { id: 8, make: 'Yamaha', model: 'FZ V4', price: 1000, type: 'bike', image: 'yamaha fz.webp' },
    { id: 9, make: 'Yamaha', model: 'MT 15', price: 1200, type: 'bike', image: 'yamaha mt15.webp' },
    { id: 10, make: 'Yamaha', model: 'R 15', price: 2000, type: 'bike', image: 'yamaha r15.webp' },
  ],
  cars: [
    { id: 1, make: 'TATA', model: 'Harrier', price: 2500, type: 'car', image: 'tata harrier.png' },
    { id: 2, make: 'TATA', model: 'Cruvv', price: 2500, type: 'car', image: 'tata cruvv.avif' },
    { id: 3, make: 'Toyota', model: 'Innova-Crysta', price: 3800, type: 'car', image: 'Toyotai.webp' },
    { id: 4, make: 'Toyota', model: 'Fortuner', price: 4000, type: 'car', image: 'toyotaf.jpg' },
    { id: 5, make: 'MG', model: 'Hector', price: 3000, type: 'car', image: 'MG Hector.avif' },
    { id: 6, make: 'KIA', model: 'Sonet', price: 3000, type: 'car', image: 'kia sonet.jpeg' },
    { id: 7, make: 'Mahindra', model: 'THAR', price: 4500, type: 'car', image: 'mahindra thar.jpeg' },
    { id: 8, make: 'Mahindra', model: 'Scorpio', price: 3500, type: 'car', image: 'mahindra scorpio.webp' },
    { id: 9, make: 'Maruthi Suzuki', model: 'Swift', price: 2000, type: 'car', image: 'Suzuki Swift.avif' },
    { id: 10, make: 'Maruthi Suzuki', model: 'Ertiga', price: 3000, type: 'car', image: 'Suzuki  ertiga.webp' },

  ],
  cargo: [
    { id: 1, make: 'TATA', model: ' Ace', price: 5000, type: 'cargo', image: 'tata ace.webp' },
    { id: 2, make: 'TATA', model: 'Large Truck', price: 20000, type: 'cargo', image: 'tata large truck.avif' },
    { id: 3, make: 'TATA', model: 'Medium Truck', price: 10000, type: 'cargo', image: 'Tata-Medium-Truck.png' },
    { id: 4, make: 'TATA', model: 'Signa Tipper', price: 15000, type: 'cargo', image: 'tata signa tipper.avif' },
    { id: 5, make: 'Mahindra', model: 'Bolero', price: 6000, type: 'cargo', image: 'mahindra-bolero.jpg' },
    { id: 6, make: 'Mahindra', model: 'Jeeto', price: 3000, type: 'cargo', image: 'mahindra jeeto.webp' },
    { id: 7, make: 'Mahindra', model: 'Furio', price: 10000, type: 'cargo', image: 'mahindra furio.jpg' },
    { id: 8, make: 'Mahindra', model: 'Large Truck', price: 20000, type: 'cargo', image: 'mahindra large container truck.jpeg' },
    { id: 9, make: 'Ashok Leyland', model: 'Dost+', price: 5000, type: 'cargo', image: 'ashok leyland mini truck.webp' },
    { id: 10, make: 'Ashok Leyland', model: 'Large Truck', price: 20000, type: 'cargo', image: 'ashok leyland large truck.jpg' },
  ],
};